test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  database: image_api_test
  username: image
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: image_api
  host: 127.0.0.1
  username: image
  password: postgres
